update post methods, trim httputils
ArkEcosystem/ark-java pull request #34
Opened 2018-02-09 07:11 UTC by cdvallejo

get, post requests should be really easy now. the last thing to do is to replace the `Model` objects in the current `<T>Response` buckets being used for the different controllers with the new `Response` objects and return a real object from the dto.

2018-02-09 07:12 UTC, cdvallejo commented on src/main/java/io/ark/core/model/Account.java
> +  private int unconfirmedSignature;
Sorry for this massacre. I'm going to add some editor configs probably in a contribution area along with checkstyle rules so this nastiness doesn't happen again. (i'll fix this in the next pr no need for a tiny commit for this)

2018-02-11 02:44 UTC, cdvallejo commented
after those style changes the pr is quite large but mostly just indentation changes etc. going to branch off here and work on peer selection methods as well as read up on v2 serialization. will open another pr with those changes.

2018-02-11 10:09 UTC, dafty requested changes
We need to consider our types for amounts (balances, values etc) and try to make them generic. This will make it more consistent to work with and prevent things like integer overflows when sending / retrieving large amounts.

2018-02-11 10:09 UTC, dafty commented on src/main/java/io/ark/core/model/Transaction.java
> +    return new TransactionDTO(id, type, timestamp, amount, fee, recipientId, senderPublicKey,
Can we get rid of the 80 char line wrapping rule. I feel like it's a legacy convention and just makes code nasty to look at while no longer serving any functional purpose.

2018-02-11 10:09 UTC, dafty commented on src/main/java/io/ark/core/requests/AccountManager.java
> +    return String.join(" ", Crypto.getPassphrase());
I don't think this does anything.

2018-02-11 10:09 UTC, dafty commented
We need to consider our types for amounts (balances, values etc) and try to make them generic. This will make it more consistent to work with and prevent things like integer overflows when sending / retrieving large amounts.

2018-02-11 17:09 UTC, cdvallejo commented
@dafty do you want to then keep all units as `long` then since that's what they come back as? i was doing the conversions to the GArk(?) for them on some methods and not others so yeah i feel the concern.

2018-02-11 19:27 UTC, cdvallejo commented
@dafty 

- Updated wrap length to 240 (basically removed the constraint since 240 is huge IMO)
- Remove all conversions from managers (long in response is used)

2018-02-12 10:33 UTC, dafty commented
@cdvallejo thanks!

2018-02-12 10:33 UTC, dafty approved these changes

2018-02-12 10:33 UTC, merged

2018-02-12 11:25 UTC, dafty commented
I think long is a good replacement for now since all amounts returned are natural numbers based (no decimals).

In the future, we could overload utility functions such as `createTransaction` with an `Denomination.ARKTOSHI` or `Denomination.ARK` enum which accepts other datatypes (like a double) and do the conversion within the function itself:

`createTransaction(Denomination.ARKTOSHI,  long: 1)`

would be the equivalent to:

 `createTransaction(Denomination.ARK, double: 0.00000001)`